from totp import get_totp_token

EMAIL="f.palacios.arriaga@gmail.com"
SECRET_KEY = "MM4TIYZXGFSTMMJXGEZDAYTGGQ4TGYJTGYYTMZLEMMZDEMJTGUZDIZJYMNSTCZLCGUZDKNTEMI2DAYRWGEYGIZRRG44TOY3GMJRDMOI="
RANDOM_SEQUENCE = ['F', 'Y', '4', '2'] # Circle, Diamond, Infinity, S_Shape

print(get_totp_token(SECRET_KEY, RANDOM_SEQUENCE))
SECRET_KEY = SECRET_KEY.replace(RANDOM_SEQUENCE[0], RANDOM_SEQUENCE[1])
SECRET_KEY = SECRET_KEY.replace(RANDOM_SEQUENCE[2], RANDOM_SEQUENCE[3])
print("New Sequence = ", SECRET_KEY)